config/routes.rb
Rails.application.routes.draw do


  get 'sessions/new'
  get 'stores/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :stores
  resources :reviews,          only: [:create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :store
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :store_id, presence: true
  validates :content, length:{maximum: 1000}
  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                        message: "must be a valid image format" },
                        size:         { less_than: 5.megabytes,
                                        message: "should be less than 5MB" }

  # 表示用のリサイズ済み画像を返す
def display_image
  image.variant(resize:'500x500').processed
end
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence:true, length:{maximum: 50}
  validates :title, length:{maximum: 255}
  validates :introduction, length:{maximum: 1000}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name, presence: true, length:{maximum: 50}
  validates :email, presence: true, length:{maximum: 255},
                  uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length:{minimum: 6}

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # 試作feedの定義
  # 完全な実装は次章の「ユーザーをフォローする」を参照
  def feed
    Review.where("user_id = ?", id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper


  private

    # ユーザーのログインを確認する
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
    @review = current_user.reviews.build(review_params)
    @review.image.attach(params[:review][:image])
    if @review.save
      flash[:success] = "review created!"
      #下記リファクタリング必要
      @store = @review.store
      redirect_to @store
    else
      @store = @review.store
      @reviews = @store.reviews.paginate(page: params[:page])
      render 'stores/show'
    end
  end

  def destroy
    @review.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

  def review_params
      params.require(:review).permit(:store_id, :content, :image)
  end

  def correct_user
      @review = current_user.reviews.find_by(id: params[:id])
      redirect_to root_url if @review.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ユーザーログイン後にユーザー情報のページにリダイレクトする
      log_in(user)
      redirect_to user
    else
      # エラーメッセージを作成する
      flash.now[:danger] = 'Invalid email/password combination' # 本当は正しくない
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def contact
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def new
    @store = Store.new
  end

  def show
    @store = Store.find(params[:id])
    @review = current_user.reviews.build if logged_in?
    @reviews = @store.reviews.paginate(page: params[:page])
  end

def create
    @store = Store.new(store_params)    # 実装は終わっていないことに注意!
    if @store.save
      # 保存の成功をここで扱う。
    else
      render 'new'
    end
  end

  private

    def store_params
      params.require(:store).permit(:name, :title, :introduction)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

   def user_params
     params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返します。                   # コメント行
def full_title(page_title = '')                     # メソッド定義とオプション引数
  base_title = "mycafe"  # 変数への代入
  if page_title.empty?                              # 論理値テスト
    base_title                                      # 暗黙の戻り値
  else
    page_title + " | " + base_title                 # 文字列の結合
  end
end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user,size)
  gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  image_tag(gravatar_url,alt: user.email, class:"gravatar")
 end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "ヘルプ",   '#' %></li>
      <li><%= link_to "お問い合わせ", '#' %></li>
      <li><%= link_to "お店の登録",'#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "My Cafe", root_path, id: "logo" %>

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ヘルプ", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "マイページ", current_user %></li>
          <li class='dropdown'>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= gravatar_for current_user,25 %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン/無料会員登録", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/reviews/_review.html.erb
<li id="review-<%= review.id %>">
  <span class="content">
    <% if controller.controller_name == 'users' && controller.action_name == 'show'%>
      <span class="store"><%= link_to review.store.name, review.store %></span>
    <% elsif controller.controller_name == 'stores' && controller.action_name == 'show' %>
      <h4><%= link_to review.user.name, review.user %></h4>
    <% else %>
      <h4><%= link_to review.user.name, review.user %></h4>
      <span class="store"><%= link_to review.store.name, review.store %></span>
    <% end %>
    <%= review.content %>
    <%= image_tag review.display_image if review.image.attached? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(review.created_at) %> ago.
    <% if controller.controller_name == 'users' && controller.action_name == 'show' &&current_user?(review.user) %>
      <%= link_to "delete", review, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/reviews/index.html.erb
<% provide(:title, 'All reviews') %>
<h1>All reviews</h1>

<%= will_paginate %>

<ul class="users">
  <% @reviews.each do |review| %>
    <li>
      <%= review.content %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="reviews">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_review_form.html.erb
<%= form_for(@review) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
    <%= f.hidden_field :store_id, value: @store.id %>
  <div class="field">
    <%= f.text_area :content, placeholder: "レビューを投稿してみよう..." %>
  </div>
  <%= f.submit '投稿', class: "btn btn-primary" %>
  <span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
<% end %>

<script type="text/javascript">
  $("#review_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#review_image").val("");
    }
  });
</script>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<%= provide(:title, "help") %>
  <head>
    <title>mycafeの使い方</title>
  </head>
  <div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>
  </div>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>

    <h2>
      This is the home page for the
      <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

  <%= image_tag "top.jpg", size: '800x400'%>

<% if logged_in? %>
  <div class="col-md-8">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>
  <% end %>
</div>

app/views/stores/new.html.erb
<% provide(:title, '店の登録') %>
<h1>店の登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@store) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :intorduction %>
      <%= f.text_field :introduction, size: "100x50"%>

      <%= f.submit "登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/stores/show.html.erb
<div class="row">
  <h3 class="storename">
    <%= @store.name %>
  </h3>
  <h4>
    <%= @store.title %>
  </h4>
  <h5>
    <%= @store.introduction %>
  </h5>
  <% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="review_form">
        <%= render 'shared/review_form' %>
      </section>
    </aside>
  </div>
  <% else %>
    <h4><%= link_to 'ユーザ登録', signup_path %>して、レビューを書こう！</h4>
  <% end %>
  <div class="col-md-8">
      <h3>reviews (<%= @store.reviews.count %>)</h3>
      <ol class="reviews">
        <%= render @reviews %>
      </ol>
      <%= will_paginate @reviews %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, '会員登録') %>
<h1>会員登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user,80 %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
      <h3>reviews (<%= @user.reviews.count %>)</h3>
      <ol class="reviews">
        <%= render @reviews %>
      </ol>
      <%= will_paginate @reviews %>
  </div>
</div>